import type { DeviceItem } from './types';

export const deviceList: DeviceItem[] = [
  {
    id: 'air-conditioner',
    name: 'Кондиционер',
    imagePath: '/images/smart-devices/air-conditioner.png',
    description: 'Охлаждает или обогревает помещение по температуре и расписанию.',
    placementTips: 'Лучше размещать на внешней стене, не направляя поток воздуха на кровать или рабочее место.',
  },
  {
    id: 'alarm-siren',
    name: 'Сигнализация',
    imagePath: '/images/smart-devices/alarm-siren.png',
    description: 'Подает громкий звуковой сигнал при тревоге, отпугивая нарушителей.',
    placementTips: 'Ставьте в центральной зоне квартиры или у входа, чтобы звук хорошо слышался во всех комнатах.',
  },
  {
    id: 'camera',
    name: 'Камера',
    imagePath: '/images/smart-devices/camera.png',
    description: 'Передает видео и записывает события для контроля дома и безопасности.',
    placementTips: 'Оптимально у входной двери, в коридоре или на обзорной точке комнаты без слепых зон.',
  },
  {
    id: 'door-window-senser',
    name: 'Датчик двери/окна',
    imagePath: '/images/smart-devices/door-window-senser.png',
    description: 'Фиксирует открытие и закрытие двери или окна.',
    placementTips: 'Крепите на раму и створку максимально близко друг к другу, особенно на входной двери и окнах первого этажа.',
  },
  {
    id: 'motion-senser',
    name: 'Датчик движения',
    imagePath: '/images/smart-devices/motion-senser.png',
    description: 'Определяет движение и запускает сценарии: свет, уведомления, охрану.',
    placementTips: 'Размещайте на высоте около 2-2.4 м в проходных зонах, направляя на маршрут движения.',
  },
  {
    id: 'smart-hub',
    name: 'Панель управления',
    imagePath: '/images/smart-devices/smart-hub.png',
    description: 'Центр управления, который связывает устройства и сценарии в одной системе.',
    placementTips: 'Ставьте ближе к центру квартиры и подальше от металлических шкафов для стабильного сигнала.',
  },
  {
    id: 'smart-led',
    name: 'Умная LED-лента',
    imagePath: '/images/smart-devices/smart-led.png',
    description: 'Создает декоративную или функциональную подсветку с управлением яркостью и цветом.',
    placementTips: 'Лучше размещать в нишах, под шкафами и по контуру мебели, где не видны диоды напрямую.',
  },
  {
    id: 'smart-light',
    name: 'Умный светильник',
    imagePath: '/images/smart-devices/smart-light.png',
    description: 'Управляет освещением: яркостью, цветовой температурой и сценариями.',
    placementTips: 'Ставьте в основных зонах освещения комнаты и комбинируйте с обычным выключателем или реле.',
  },
  {
    id: 'smart-lock',
    name: 'Умный замок',
    imagePath: '/images/smart-devices/smart-lock.png',
    description: 'Позволяет открывать дверь кодом, картой, приложением или по сценарию.',
    placementTips: 'Устанавливайте на основную входную дверь с хорошим механическим цилиндром и резервным доступом.',
  },
  {
    id: 'smart-plug',
    name: 'Умная розетка',
    imagePath: '/images/smart-devices/smart-plug.png',
    description: 'Включает и отключает подключенную нагрузку, иногда считает потребление энергии.',
    placementTips: 'Используйте для торшеров, бытовой техники и устройств у которых безопасно удаленное включение.',
  },
  {
    id: 'smart-switch',
    name: 'Умный выключатель',
    imagePath: '/images/smart-devices/smart-switch.png',
    description: 'Управляет светом и может запускать сценарии по нажатию.',
    placementTips: 'Ставьте в привычных точках входа в комнату, на стандартной высоте обычного выключателя.',
  },
  {
    id: 'smart-thermostat',
    name: 'Умный термостат',
    imagePath: '/images/smart-devices/smart-thermostat.png',
    description: 'Поддерживает заданную температуру и автоматизирует климат по расписанию.',
    placementTips: 'Размещайте на внутренней стене на высоте 1.2-1.5 м, вдали от солнечных лучей и радиаторов.',
  },
  {
    id: 'smoke-senser',
    name: 'Датчик дыма',
    imagePath: '/images/smart-devices/smoke-senser.png',
    description: 'Обнаруживает дым и отправляет тревогу для раннего предупреждения пожара.',
    placementTips: 'Крепите на потолке в коридоре и возле кухни, но не прямо над плитой, чтобы избежать ложных срабатываний.',
  },
  {
    id: 'temp-sense',
    name: 'Датчик температуры',
    imagePath: '/images/smart-devices/temp-sense.png',
    description: 'Измеряет температуру для климатических сценариев и мониторинга.',
    placementTips: 'Ставьте в зоне средней температуры комнаты, не рядом с окнами, батареями и кондиционером.',
  },
  {
    id: 'water-leak-senser',
    name: 'Датчик протечки воды',
    imagePath: '/images/smart-devices/water-leak-senser.png',
    description: 'Фиксирует появление воды и запускает оповещение или аварийное перекрытие.',
    placementTips: 'Размещайте на полу у стиральной машины, под раковиной, у бойлера и коллектора.',
  },
];
