import type { TutorialStep } from './types';

export const tutorialSteps: TutorialStep[] = [
  {
    id: 'create-room',
    title: 'Шаг 1: Создай комнату',
    description: 'Это основа проекта: сначала создаем учебную комнату для дальнейших действий.',
    selector: '[data-tutorial="tutorial-create-room"]',
    condition: (ctx) => ctx.hasRoom,
    requiresAction: true,
  },
  {
    id: 'toolbar-cursor',
    title: 'Курсор',
    description: 'Выделение и работа с уже созданными объектами.',
    selector: '[data-tutorial="tutorial-tool-cursor"]',
    condition: () => true,
    requiresAction: false,
  },
  {
    id: 'toolbar-snap',
    title: 'Привязка',
    description: 'Помогает ровно выравнивать элементы на полотне.',
    selector: '[data-tutorial="tutorial-tool-snap"]',
    condition: () => true,
    requiresAction: false,
  },
  {
    id: 'toolbar-rectangle',
    title: 'Прямоугольник',
    description: 'Основной инструмент рисования зон и блоков.',
    selector: '[data-tutorial="tutorial-tool-rectangle"]',
    condition: () => true,
    requiresAction: false,
  },
  {
    id: 'toolbar-line',
    title: 'Линия',
    description: 'Удобна для перегородок и трассировки.',
    selector: '[data-tutorial="tutorial-tool-line"]',
    condition: () => true,
    requiresAction: false,
  },
  {
    id: 'toolbar-eraser',
    title: 'Ластик',
    description: 'Удаление лишних элементов на плане.',
    selector: '[data-tutorial="tutorial-tool-eraser"]',
    condition: () => true,
    requiresAction: false,
  },
  {
    id: 'toolbar-color',
    title: 'Цвет',
    description: 'Помогает визуально разделять элементы по смыслу.',
    selector: '[data-tutorial="tutorial-tool-color"]',
    condition: () => true,
    requiresAction: false,
  },
  {
    id: 'toolbar-fullscreen',
    title: 'Полный экран',
    description: 'Разворачивает полотно на весь экран для более удобной работы.',
    selector: '[data-tutorial="tutorial-tool-fullscreen"]',
    condition: () => true,
    requiresAction: false,
  },
  {
    id: 'toolbar-furniture',
    title: 'Мебель',
    description: 'Открывает каталог предметов для расстановки.',
    selector: '[data-tutorial="tutorial-open-furniture"]',
    condition: () => true,
    requiresAction: false,
  },
  {
    id: 'toolbar-devices',
    title: 'Устройства',
    description: 'Открывает список умных девайсов.',
    selector: '[data-tutorial="tutorial-open-devices"]',
    condition: () => true,
    requiresAction: false,
  },
  {
    id: 'create-rectangle',
    title: 'Шаг 2: Создай прямоугольник',
    description: 'Выбери инструмент «Прямоугольник» и нарисуй фигуру на полотне.',
    selector: '[data-tutorial="tutorial-tool-rectangle"]',
    condition: (ctx) => ctx.hasRectangle,
    requiresAction: true,
  },
  {
    id: 'add-furniture',
    title: 'Шаг 3: Добавь мебель',
    description: 'Открой список мебели и добавь любой объект на полотно.',
    selector: '[data-tutorial="tutorial-open-furniture"]',
    condition: (ctx) => ctx.hasAddedFurniture,
    requiresAction: true,
  },
  {
    id: 'place-device',
    title: 'Шаг 4: Размести устройство',
    description: 'Открой список умных устройств и добавь устройство на полотно.',
    selector: '[data-tutorial="tutorial-open-devices"]',
    condition: (ctx) => ctx.hasAddedDevice,
    requiresAction: true,
  },
];
